### ISSUE TITLE
support for cocoa pods

### ISSUE THREAD

**Issue by magellan314** [troystribling/BlueCap#10]
More of a request rather than an issue. Do you intend to add support for cocoa pods for BlueCap? It makes updates and new features / bug fixes much easier to incorporate than manually adding to projects.

**Comment by troystribling** [comment]
I will look into it. When I started Cocoa Pods did not support swift. Will update issue when done.

**Comment by mhle** [comment]
:+1:

**Comment by rph8** [comment]
This is definitely a great idea. It makes updating BlueCap much easier, because one only has to do a "pod install". CocoaPods has also supported Swift for some time now.

**Comment by cpatterson** [comment]
:+1:

**Comment by troystribling** [comment]
I am close to starting this. Possibly in a week or two.

**Comment by bshewmak** [comment]
I realize these comments are month's old, but is there still any chance that you are still going to add the cocoa pods support? As said previously, it makes it that much easier to implement into a current project.

**Comment by troystribling** [comment]
I intend to add cocoa pods support. I am currently finishing up a review of test cases. After that I will add cocoa pods support.

**Comment by troystribling** [comment]
Just release version 0.1.0 pod. Carthage is also supported. Still need to update documentation.
