### ISSUE TITLE
Swift 2.2 deprecation warnings

### ISSUE THREAD

**Issue by cbowns** [troystribling/BlueCap#27]
Two methods use `var` parameters; these will be removed in Swift 3.

![screen shot 2016-02-24 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/474/13306076/5a95f98e-db15-11e5-9100-36dcac2f0db0.png)

![screen shot 2016-02-24 at 4 39 37 pm](https://cloud.githubusercontent.com/assets/474/13306066/4174d7fe-db15-11e5-9df2-3a8dbdc6f7d7.png)

**Comment by troystribling** [comment]
How do you turn on 3.0 deprecation warnings? I am not getting them.

**Comment by cbowns** [comment]
If you build with Xcode 7.3 beta 4 or beta 5, it spits them out. https://developer.apple.com/xcode/download/

Bear in mind, some of the migrations in beta 5 (a.k.a. Swift 2.2 beta-ish?) are *not* backwards to Swift 2.1/Xcode 7.2.

**Comment by troystribling** [comment]
Master now builds without warnings for Xcode 7.3.
