### ISSUE TITLE
Replacement For `WhenPowerOn` in next_release branch

### ISSUE THREAD

**Issue by hockeybro12** [troystribling/BlueCap#40]
Hello,

I am wondering what the correct replacement is for WhenPowerOn/WhenPowerOff in the next_release branch. 

Previously, I had: 
`peripheralManager!.whenPowerOff().onComplete({ _ in` 
Should I have this now?
```
peripheralManager!.whenStateChanges().onComplete(completion: { (managerState) in
            if self.peripheralManager?.state == ManagerState.poweredOff {
```

And also, previously I had this, from the docs:
```
let scanningFuture = manager.whenPowerOn().flatmap {
    manager.startScanningForServiceUUIDs([serviceUUID])
}
```

What should I have now?

Thanks

**Comment by troystribling** [comment]
Yes something like

peripheralManager!.whenStateChanges().onComplete(completion: { (managerState) in
   switch state {
      case .poweredOn:
          manager.startScanningForServiceUUIDs([serviceUUID])
   }
}
