### ISSUE TITLE
CBCentralManagerInjectable protocol conformance error

### ISSUE THREAD

**Issue by rameswarios** [troystribling/BlueCap#44]
I'm developing my app in Swift 3.0 and added BlueCapKit using CocoaPods. 
I've updated the flag '**Use Legacy Swift Language Version**' to '**Yes**' for BlueCap.

However I'm getting this particular issue which says  **Type 'CBCentralManager' does not conform to protocol 'CBCentralManagerInjectable'**

And this happens due to the **'state'** variable.

Here's a screenshot of the error to help you. Can you please help solve this?

![screen shot 2016-11-15 at 10 59 21 pm](https://cloud.githubusercontent.com/assets/15683440/20316785/6cf6b682-ab89-11e6-9bff-1a07d2eed89b.png)

**Comment by troystribling** [comment]
This is fixed on the next release branch. Current master will not work with iOS  10 because of a change in the CBCentralManager and CBPeripheralManager state variable.

**Comment by rameswar54** [comment]
Is **next_release** branch stable to integrate in project for Swift 3.0 version are need to wait?
Are you going to release in near future?

**Comment by troystribling** [comment]
I plan to release soon. The interface is stable and no more changes are
planned. I am just working through examples and fixing bugs.

**Comment by rameswarios** [comment]
Hello Troy, did you fix all the bugs?

Can I update my project which uses BlueCap already? I'm just holding on for BlueCap Swift 3 version. Or you're on the process still to fix all bugs and release soon. Any feedback shall be greatly helpful.

**Comment by troystribling** [comment]
This should be resolved with version 0.2.0.
