### ISSUE TITLE
Updates to the README

### ISSUE THREAD

**Issue by Laptopmini** [troystribling/BlueCap#46]
The podspec says the minimum target is 9.0 and the minimum Cocoapod version as 1.1.

https://github.com/troystribling/BlueCap#cocoapods
This example uses a target of 10.0, should probably be 9.0 to avoid confusion. 
Also, the library now requires CocoaPods 1.1+.

https://github.com/troystribling/BlueCap#manual
The manual installation says 8.0, should definitely be 9.0 there.

Nothing really important here obviously, but thought I'd create a ticket so you notice it. Great library by the way.

**Comment by troystribling** [comment]
Fixed, thanks.
