### ISSUE TITLE
Peripheral.connect retries even after a timeout

### ISSUE THREAD

**Issue by yostane** [troystribling/BlueCap#58]
Hi,

I noted that the peripheral.connect tries to connect even after getting a timeout. Here is a scenario.

Maintain a peripheral connected to a central A
Run peripheral.connect(timeout: 10) on central B. B cannot connect since the connection is owned by 1.
onFailed is called after the timeout on central B
central A disconnects
Central B connects but it should not because we got a timeout

Is there a way to avoid this ?
Thanks,

**Comment by troystribling** [comment]
Thanks for finding a bug. This is fixed in pod 0.52.
