### ISSUE TITLE
Resources are insufficient when writing characteristic

### ISSUE THREAD

**Issue by soonfay** [troystribling/BlueCap#59]
Hi Troy,

I have this issue everytime when I try to write a command. I cant really find anything helpful regarding to this issue. 

![insufficient_error](https://cloud.githubusercontent.com/assets/8239722/23629382/9898ff4a-0285-11e7-88b2-9f073ac67f73.jpg)

**Comment by troystribling** [comment]
This is not a framework error. It is a CoreBluetooth error: https://developer.apple.com/reference/corebluetooth/cbatterror.code/1518710-insufficientresources

Here is some talk about it. Find9ing any information seems difficult.
http://stackoverflow.com/questions/40532822/meaning-of-insufficient-resources-in-core-bluetooth.

The discussions indicates the discussion indicates that it may be comping from the the device not the phone.

Writes work in examples and on hardware I have tested. Not sure I can do anything without the hardware.

**Comment by soonfay** [comment]
Yeah, that's the only discussion I can find online. 
Ok, thanks for the quick response.
