### ISSUE TITLE
Get CBPeripheral from BlueCapKit.Peripheral?

### ISSUE THREAD

**Issue by Soulphalanx** [troystribling/BlueCap#63]
Anyway to get a CBPeripheral from BlueCapKit.Peripheral? I'm using a framework to upgrade the firmware OTA and it only accepts CBPeripherals and I would prefer to not have to rewrite it or write another central using CoreBluetooth calls.

Thanks for your time.

**Comment by troystribling** [comment]
There is a ```cbPeripheral``` property on ```Peripheral``` but it is internal. It would have to be made public. Change would need to be made here https://github.com/troystribling/BlueCap/blob/master/BlueCapKit/Central/Peripheral.swift#L95.

**Comment by Soulphalanx** [comment]
Cool, that's what I figured. Thanks for the confirmation.
