### ISSUE TITLE
Sing in project and Podfile.lock & Manifest.lock error

### ISSUE THREAD

**Issue by saeidulysse** [troystribling/BlueCap#67]
Hello everyone, 

I have a concern and I think is very primary, I just downloaded this project and I was trying to test one of those examples, (CentralManager), but I take an error message immediately : 

> Showing Recent Issues
> diff: /../Podfile.lock: No such file or directory
> 
> Showing Recent Issues
> diff: /Manifest.lock: No such file or directory
> 
> Showing Recent Issues
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I have to say in Targets>General>Sing in, I couldn't use my Personal Team for this project. 
I just wanted to ask if it's possible to help me resurrect this concern.

**Comment by troystribling** [comment]
Did you run `pod install`? You also need to build the project with the generated workspace.
