### ISSUE TITLE
Bluetooth device with password

### ISSUE THREAD

**Issue by Y2JChamp** [troystribling/BlueCap#73]
Hello, i have to connect to a bluetooth device that requires a password.
How can i add it programmatically or display an input field to the user?

**Comment by troystribling** [comment]
Create a authentication service with password management characteristics? Make it secure so that the data is encrypted. You probably should also have your own layer of encryption.

**Comment by Y2JChamp** [comment]
Hello troy, 
do u have an example code for what you have described?

Thanks a lot

**Comment by troystribling** [comment]
There are examples that show how to set up the services and characteristics but none that implement authentication.
