### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by reshmisarma** [troystribling/BlueCap#76]
Hi,
I would like to integrate BlueCap to my project. The app needs to scan for 3 types of peripheral devices(all having different set of services), and should connect to one device from each type. These scanning and connection is happening at different time. Will the BlueCap support multiple connections? Should I keep separate instances of the manager for each connection?

**Comment by troystribling** [comment]
Yes, it does. You can manage them all in a single manager. This is done in the BluCap example app https://github.com/troystribling/BlueCap/tree/master/Examples/BlueCap.
