### ISSUE TITLE
Connect Peripheral Powered Off, 30 seconds later powered On

### ISSUE THREAD

**Issue by kaizenkaizen** [troystribling/BlueCap#81]
How would I handle the case: an already connected peripheral is powered off, 30 seconds later it is powered on again, and I want to reconnect to this peripheral?

**Comment by troystribling** [comment]
After the disconnect try to reconnect with infinite timeout and wait.

**Comment by kaizenkaizen** [comment]
Thanks! Is there a code snippet of this, that you could provide? It would be greatly appreciated.

**Comment by troystribling** [comment]
https://github.com/troystribling/BlueCap/blob/master/Documentation/CentralManager.md#central_peripheral_connection. The default timeout is infinite. Her is an example https://github.com/troystribling/BlueCap/blob/master/Examples/CentralManager/CentralManager/ViewController.swift#L106-L207
